export const ERRORS = "ERRORS";
export const SIGNUP = "SET_CURRENT_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const TOPICS = "TOPICS";

export const GET_QUESTIONS_CONTENT = "GET_QUESTIONS_CONTENT";
export const GET_ANSWERS_CONTENT = "GET_ANSWERS_CONTENT";
export const GET_FOLLOWEDQUESTIONS_CONTENT = "GET_FOLLOWEDQUESTIONS_CONTENT";
export const GET_ALL_CONTENT = "GET_ALL_CONTENT";
export const GET_ALL_CONTENT_QUESTIONS = "GET_ALL_CONTENT_QUESTIONS";
export const GET_ALL_CONTENT_ANSWERS = "GET_ALL_CONTENT_ANSWERS";
export const GET_ALL_CONTENT_FOLLOWEDQUESTIONS = "GET_ALL_CONTENT_FOLLOWEDQUESTIONS";